Pure pursuit
Tino-FRC-2473/FRC2022 pull request #21
Opened 2022-03-01 06:07 UTC by RahulBansal1112

2022-03-05 04:19 UTC, AG6GR requested changes
Please remember to push branches for #15 and #16 before merging this.

2022-03-05 04:19 UTC, AG6GR commented on src/main/java/frc/robot/trajectory/PurePursuit.java
> +	 * asdf.
?

2022-03-06 00:54 UTC, RahulBansal1112 commented
> 

We cleaned up the drive code (there's some small commented out pieces of code, but we're still using those to test the auto paths). As for the teleop states, we've written the code for it and tested it, but need to test one part of it to make sure it 100% works before we'll merge it into main.

2022-03-06 18:59 UTC, AG6GR requested changes

2022-03-06 18:59 UTC, AG6GR commented on src/main/java/frc/robot/trajectory/PurePursuit.java
> +	private final int lookaheadDistance = 8;
Constants should be static and all caps

2022-03-06 18:59 UTC, AG6GR commented on src/main/java/frc/robot/Robot.java
> +	private static final boolean RUN_COMPRESSOR = false;
Keep this true on main branch. In fact maybe we should put this on shuffleboard.

2022-03-06 19:28 UTC, AG6GR approved these changes

2022-03-06 19:42 UTC, merged