Interface
Tino-FRC-2473/FRC2022 pull request #5
Opened 2022-01-27 04:34 UTC by andrewxsimon

2022-01-31 01:51 UTC, AG6GR approved these changes
Looks like you need to rebase against main branch to resolve conflict, then force push.
`git rebase main interface`
Fix whatever needs to be fixed
`git add <whatever>`
`git push -f`

2022-02-03 04:46 UTC, tsoim commented on src/main/java/frc/robot/Robot.java
> +// import edu.wpi.first.wpilibj.shuffleboard.BuiltInWidgets;
nit: do not include commented out code

2022-02-06 19:38 UTC, AG6GR commented
Please get this rebased ASAP so that we can merge it to main.

2022-02-10 19:01 UTC, AG6GR requested changes

2022-02-10 19:01 UTC, AG6GR commented on src/main/java/frc/robot/Robot.java
> +import edu.wpi.first.cscore.CvSink;
Please put the WPILib imports under the "WPILib Imports" section.

2022-02-12 19:12 UTC, AG6GR approved these changes

2022-02-14 22:24 UTC, merged